### ISSUE TITLE
Check against steveohara

### ISSUE THREAD

**Issue by btbouwens** [j123b567/j2mod#1]
I think you might want to check if your changes are compatible with the latest version of Steve O'Hara: https://github.com/steveohara/j2mod

**Comment by j123b567** [comment]
My changes are probably not compatible with this repo but good to know about it!
I will try to replace it in my projects and delete this one. It is finally modern and well designed modbus library in java dropping all previous ugly design flaws and errors in original j2mod and jamod. Great!

**Comment by j123b567** [comment]
My software works after some modifications in my software and in Steve O'Hara's version so I can drop this repository in near feature. Thank you.
